### ISSUE TITLE
Autostart doesn't work on first run after game is started

### ISSUE THREAD

**Issue by samabam** [LiterallyMetaphorical/LiveSplit.POPTLC#11]
### Is there an existing issue for this?

- [X] I have searched the existing issues, and none exist

### Did you install the autosplitter via the LiveSplit UI?

- [X] I installed the autosplitter via LiveSplit.

### Expected Behaviour

Autostart to function on all runs.

### Actual Behaviour

Autostart works on all runs except the first one after launch. 

### Link to a video with DebugView output.

https://www.youtube.com/watch?v=pVauB3EYorg

**Comment by mitchell-merry** [comment]
Very strange.... thanks for the video

**Comment by mitchell-merry** [comment]
Could you try #13 and let me know if it fixes this?

Here's how you install it:
1. Deactivate the autosplitter in LiveSplit.
2. Download the .asl file from GitHub (I included it in this message for convenience)
3. Right click LiveSplit -> Edit Layout -> Add -> Scriptable Autosplitter
4. Edit the component and set the path to the .asl you downloaded
5. Try again and see if it helps.

If it doesn't (or somehow makes it worse), I could use another DebugView recording.

If it fixes it, let me know and I can merge that change in!

**Comment by samabam** [comment]
This issue is fixed!

**Comment by mitchell-merry** [comment]
Awesome!
