### ISSUE TITLE
First split fails sometimes

### ISSUE THREAD

**Issue by samabam** [LiterallyMetaphorical/LiveSplit.POPTLC#12]
### Is there an existing issue for this?

- [X] I have searched the existing issues, and none exist

### Did you install the autosplitter via the LiveSplit UI?

- [X] I installed the autosplitter via LiveSplit.

### Expected Behaviour

All splits to work.

### Actual Behaviour

First split fails intermittently. 

### Link to a video with DebugView output.

https://www.youtube.com/watch?v=pVauB3EYorg

**Comment by mitchell-merry** [comment]
Thanks - that's really weird, and it tells me we can't trust the way this was splitting before.

I'll change this so that it splits when you enter the area, rather than when the first quest completes (because it looks like it just doesn't)

**Comment by mitchell-merry** [comment]
Could you try again and let me know if https://github.com/LiterallyMetaphorical/LiveSplit.POPTLC/pull/14 fixed it? As in, if you see this again.

**Comment by mitchell-merry** [comment]
Gonna call this one fixed
