### ISSUE TITLE
Autosplit doesn't happen completing "Tiger and Rat" quest

### ISSUE THREAD

**Issue by ensaladorage** [LiterallyMetaphorical/LiveSplit.POPTLC#17]
### Is there an existing issue for this?

- [X] I have searched the existing issues, and none exist

### Did you install the autosplitter via the LiveSplit UI?

- [X] I installed the autosplitter via LiveSplit.

### Expected Behaviour

Talking with the old man ends the quest and livesplit should autosplit the section.

### Actual Behaviour

Nothing happens in livesplit

### Link to a video with DebugView output.

https://github.com/LiterallyMetaphorical/LiveSplit.POPTLC/assets/16151873/a890c923-ad38-4ab9-924b-ad895562bfaf

[Tiger.LOG](https://github.com/LiterallyMetaphorical/LiveSplit.POPTLC/files/13981967/Tiger.LOG)

**Comment by mitchell-merry** [comment]
The Tiger and the Rat split completed correctly.

It looks like the Abducted Prince split did _not_ though, could you send a video of what happens there?

**Comment by ensaladorage** [comment]
Haaaa thats right! Lert me check. HMM I see that I am using Battlefield as 1st split and everything is splitting correct but counting Lost in mount Qas as Battlefield split. Chekc the video. 
So Maybe I just remove the Battlefield split?

https://github.com/LiterallyMetaphorical/LiveSplit.POPTLC/assets/16151873/2dc4f181-f53a-42ae-a625-81ad0710f43d

**Comment by ensaladorage** [comment]
Found the problem. Battlefield quest is not showing in screen because i am leaving the room very fast. 

https://github.com/LiterallyMetaphorical/LiveSplit.POPTLC/assets/16151873/600fdb5c-ea83-4a6a-aa74-13e7e5d1951c

**Comment by mitchell-merry** [comment]
What you have as "Battlefield" is indeed meant to split once you leave the palace - the setting name has "Battlefield + Thomyris Palace".

The Abducted Prince split is meant to happen after Vahram. Could you should that?

**Comment by ensaladorage** [comment]
Here it is the video. After completing the boss it creates a split on Lost in Qaf but don't know if thats correct. Then taking the Shadow run Abducted prince quest showed up.
https://github.com/LiterallyMetaphorical/LiveSplit.POPTLC/assets/16151873/4f50887d-2cdd-4e36-9629-a92654a17205

**Comment by ensaladorage** [comment]
Sorry about the mess. Here it is. 

https://github.com/LiterallyMetaphorical/LiveSplit.POPTLC/assets/16151873/5d8a13f9-1eb5-486a-9e7f-118f018d1abb

**Comment by mitchell-merry** [comment]
How do you skip all that? 

That should be a simple fix. I'll post an ASL + settings you can try

**Comment by ensaladorage** [comment]
Mashing a lot aerial dash hahahaha. Okay thanks!

**Comment by mitchell-merry** [comment]
GMP is testing the asl for the subtitles fix so I chucked in the possible fix for this in there too. Will report back

**Comment by mitchell-merry** [comment]
It's not clear, but this may have been resolved by #16 (GMP missed the fight skip lul). Please re-tick the settings (they would have unticked you) and try again and let me know if it works again

**Comment by mitchell-merry** [comment]
Have heard reports this is working. Closing now
